-- Generated by lib/shipping-filter-sql.js. Validate against classifyShipping before changing.
CREATE OR REPLACE FUNCTION dataplus_shipping_class(item jsonb, max_length numeric, max_girth numeric, max_weight numeric, honor_freight boolean)
RETURNS text LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $shipping$
DECLARE
  value text;
  m_packagelength numeric;
  m_packagewidth numeric;
  m_packageheight numeric;
  m_packageweight numeric;
  m_itemlength numeric;
  m_itemwidth numeric;
  m_itemheight numeric;
  m_itemweight numeric;
BEGIN
  value := coalesce(item->>'packageLength', item->'raw'->>'packageLength', item->>'package_length', item->'raw'->>'package_length', item->'original'->>'package_length', '');
    m_packagelength := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  value := coalesce(item->>'packageWidth', item->'raw'->>'packageWidth', item->>'package_width', item->'raw'->>'package_width', item->'original'->>'package_width', '');
    m_packagewidth := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  value := coalesce(item->>'packageHeight', item->'raw'->>'packageHeight', item->>'package_height', item->'raw'->>'package_height', item->'original'->>'package_height', '');
    m_packageheight := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  value := coalesce(item->>'packageWeight', item->'raw'->>'packageWeight', item->>'package_weight', item->'raw'->>'package_weight', item->'original'->>'package_weight', '');
    m_packageweight := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  value := coalesce(item->>'itemLength', item->'raw'->>'itemLength', item->>'item_length', item->'raw'->>'item_length', item->'original'->>'item_length', '');
    m_itemlength := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  value := coalesce(item->>'itemWidth', item->'raw'->>'itemWidth', item->>'item_width', item->'raw'->>'item_width', item->'original'->>'item_width', '');
    m_itemwidth := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  value := coalesce(item->>'itemHeight', item->'raw'->>'itemHeight', item->>'item_height', item->'raw'->>'item_height', item->'original'->>'item_height', '');
    m_itemheight := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  value := coalesce(item->>'itemWeight', item->'raw'->>'itemWeight', item->>'item_weight', item->'raw'->>'item_weight', item->'original'->>'item_weight', '');
    m_itemweight := case when btrim(value) ~ '^[+]?[0-9]*[.]?[0-9]+([eE][+-]?[0-9]+)?$' then greatest(0, value::numeric) else 0 end;
  RETURN (case when coalesce(item->>'shippingClassOverride', item->'raw'->>'shippingClassOverride') = 'ltl' then 'ltl'
    when honor_freight and (coalesce(item->>'requiresFreight', item->'raw'->>'requiresFreight') in ('true','1') or coalesce(item->>'freightOnly', item->'raw'->>'freightOnly') in ('true','1') or coalesce(item->>'supplierFreightRequired', item->'raw'->>'supplierFreightRequired') in ('true','1') or coalesce(coalesce(item->>'shipMode', item->'raw'->>'shipMode'), '') ~* '(^|"|\[)[[:space:]]*(ltl|l tl|freight|truck|truckload|pallet|freight only|ltl only)[[:space:]]*("|\]|$)' or coalesce(coalesce(item->>'ship_mode', item->'raw'->>'ship_mode'), '') ~* '(^|"|\[)[[:space:]]*(ltl|l tl|freight|truck|truckload|pallet|freight only|ltl only)[[:space:]]*("|\]|$)' or coalesce(coalesce(item->>'sourceShippingMethod', item->'raw'->>'sourceShippingMethod'), '') ~* '(^|"|\[)[[:space:]]*(ltl|l tl|freight|truck|truckload|pallet|freight only|ltl only)[[:space:]]*("|\]|$)' or coalesce(item->'original'->>'ship_mode', '') ~* '(^|"|\[)[[:space:]]*(ltl|l tl|freight|truck|truckload|pallet|freight only|ltl only)[[:space:]]*("|\]|$)') then 'ltl'
    when greatest((case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagelength else m_itemlength end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagewidth else m_itemwidth end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packageheight else m_itemheight end)) > max_length
      or (least((case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagelength else m_itemlength end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagewidth else m_itemwidth end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packageheight else m_itemheight end)) > 0 and (2 * ((case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagelength else m_itemlength end) + (case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagewidth else m_itemwidth end) + (case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packageheight else m_itemheight end)) - greatest((case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagelength else m_itemlength end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagewidth else m_itemwidth end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packageheight else m_itemheight end))) > max_girth)
      or coalesce(nullif(m_packageweight, 0), m_itemweight) > max_weight then 'ltl'
    when not (least((case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagelength else m_itemlength end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packagewidth else m_itemwidth end),(case when greatest(m_packagelength,m_packagewidth,m_packageheight) > 0 then m_packageheight else m_itemheight end)) > 0) or coalesce(nullif(m_packageweight, 0), m_itemweight) = 0 then 'missing_measurements'
    else 'parcel' end);
END;
$shipping$;
