import { useEffect, useState } from "react"
import { Download, MoreHorizontal, Plus, RefreshCw, Save, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { Button } from "./ui/button"
import { Badge } from "./ui/badge"
import { Checkbox } from "./ui/checkbox"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "./ui/dialog"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "./ui/dropdown-menu"
import { Input } from "./ui/input"
import { Label } from "./ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs"
import { Textarea } from "./ui/textarea"
import type { ReactNode } from "react"
import { journalBalances } from "../lib/journal-balances"

type Line = { account: string; debitMinor: number; creditMinor: number; description: string }
type Observation = { id: string; key: string; kind: string; currency: string; amountMinor: number | null; certainty: string; capturedAt: string; sourcePath: string; postingPolicy?: string; returnId?: string }
type Journal = { id: string; date: string; description: string; evidence: string; currency: string; status: string; lines: Line[]; sourceIds: string[]; returnId?: string; reverses?: string; adjusts?: string; createdBy: string; postedBy?: string }
type Batch = { id: string; destinationId: string; destinationName: string; entries: Journal[]; createdAt: string; checksum: string; importedAt?: string; importReference?: string }
type Config = { version: number; closedThrough: string; destinations: { id: string; name: string; mappings: Record<string, string> }[] }
type Data = { ledger: { observations: Observation[]; journals: Journal[]; batches: Batch[]; audit: { id: string; action: string; actor: string; at: string; reference: string }[] }; config: Config; accounts: Record<string, string>; currencies: Record<string, number>; can: Record<string, boolean> }
type DraftLine = { account: string; debit: string; credit: string; description: string }
const emptyLine = (): DraftLine => ({ account: "", debit: "", credit: "", description: "" })
const today = () => new Date().toISOString().slice(0, 10)
const requestId = () => crypto.randomUUID()
const dateText = (value: string) => Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString() : "Not available"
async function api<T>(path: string, body?: unknown, method = "POST"): Promise<T> {
  const response = await fetch(path, body === undefined ? undefined : { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) })
  const result = await response.json()
  if (!response.ok) throw new Error(result.error || `Request failed: ${response.status}`)
  return result
}

export function AccountingLedger({ orderId, returnId, currency = "USD", reported }: { orderId: string; returnId?: string; currency?: string; reported: ReactNode }) {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState("")
  const [busy, setBusy] = useState(false), [view, setView] = useState(() => new URLSearchParams(window.location.search).get("transactionsView") === "exports" ? "exports" : "reported")
  const [draft, setDraft] = useState<{ requestId: string; date: string; currency: string; description: string; evidence: string; sourceIds: string[]; lines: DraftLine[]; adjusts?: string } | null>(null)
  const [action, setAction] = useState<{ kind: string; entry: Journal; date: string; reason: string; confirm: boolean; requestId: string } | null>(null)
  const [config, setConfig] = useState<Config | null>(null), [destination, setDestination] = useState("general")
  const [selected, setSelected] = useState<string[]>([]), [exportKey, setExportKey] = useState(requestId)
  const [importBatch, setImportBatch] = useState<Batch | null>(null), [importReference, setImportReference] = useState("")
  const root = `/api/accounting/orders/${encodeURIComponent(orderId)}`
  const load = async () => {
    try { const next = await api<Data>(root); setData(next); setConfig(next.config); setError("") }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to load ledger") }
  }
  useEffect(() => { void load() }, [orderId])
  const run = async (path: string, body: unknown, done?: () => void, method = "POST") => {
    setBusy(true)
    try { await api(path, body, method); done?.(); await load(); toast.success("Accounting record saved.") }
    catch (e) { toast.error(e instanceof Error ? e.message : "Accounting operation failed") }
    finally { setBusy(false) }
  }
  const observations = data ? [...new Map(data.ledger.observations.map(row => [row.key, row])).values()].filter(row => !returnId || row.returnId === returnId) : []
  const journals = data?.ledger.journals.filter(row => !returnId || row.returnId === returnId || row.sourceIds.some(key => data.ledger.observations.find(source => source.id === key)?.returnId === returnId)) || []
  const batches = data?.ledger.batches.filter(row => !returnId || row.entries.some(entry => journals.some(journal => journal.id === entry.id))) || []
  const money = (amount: number | null, code: string) => amount === null ? "Not available" : new Intl.NumberFormat("en-US", { style: "currency", currency: code }).format(amount / 10 ** (data?.currencies[code] ?? 2))
  const newDraft = (adjusts?: Journal) => setDraft({ requestId: requestId(), date: today(), currency: adjusts?.currency || currency, description: "", evidence: "", sourceIds: [], lines: [emptyLine(), emptyLine()], ...(adjusts ? { adjusts: adjusts.id } : {}) })
  const exported = (journalId: string) => data?.ledger.batches.some(batch => batch.destinationId === destination && batch.entries.some(entry => entry.id === journalId))
  const balance = draft ? journalBalances(draft.lines, data?.currencies[draft.currency]) : null
  const entrySources = (entry: Journal) => <section className="grid gap-2 border-t pt-3 text-sm">
    {(entry.reverses || entry.adjusts) && <p className="break-all">{entry.reverses ? "Reverses" : "Adjusts"}: {entry.reverses || entry.adjusts}</p>}
    {entry.returnId && <p className="break-all">Return: {entry.returnId}</p>}
    {entry.sourceIds.map(key => { const source = data?.ledger.observations.find(row => row.id === key); return source ? <div className="grid gap-1" key={key}><span>{source.kind} / {money(source.amountMinor, source.currency)} / {source.certainty}</span><span className="break-all text-xs text-muted-foreground">{source.sourcePath} / {dateText(source.capturedAt)} / {source.id}</span></div> : null })}
    {!entry.sourceIds.length && <p className="text-muted-foreground">Manual entry supported by the recorded evidence.</p>}
  </section>
  const lineTable = (entry: Journal) => <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Account</TableHead><TableHead className="text-right">Debit</TableHead><TableHead className="text-right">Credit</TableHead></TableRow></TableHeader><TableBody>{entry.lines.map((line, index) => <TableRow key={index}><TableCell className="whitespace-normal">{data?.accounts[line.account] || line.account}<p className="text-xs text-muted-foreground">{line.description}</p></TableCell><TableCell className="text-right">{money(line.debitMinor, entry.currency)}</TableCell><TableCell className="text-right">{money(line.creditMinor, entry.currency)}</TableCell></TableRow>)}</TableBody></Table></div>
  return <Tabs value={view} onValueChange={setView} className="min-w-0">
    <TabsList className="flex flex-wrap justify-start gap-1 group-data-horizontal/tabs:h-auto [&>[role=tab]]:h-8"><TabsTrigger value="reported">Reported amounts</TabsTrigger><TabsTrigger value="entries">Ledger entries</TabsTrigger><TabsTrigger value="exports">Export history</TabsTrigger><TabsTrigger value="settings">Account mappings</TabsTrigger></TabsList>
    <TabsContent value="reported" className="min-w-0 pt-3">{reported}</TabsContent>
    {view !== "reported" && error && <p role="alert" className="text-sm text-destructive">{error}<Button variant="ghost" size="sm" onClick={() => void load()}>Retry</Button></p>}
    {view !== "reported" && !data && !error && <p role="status">Loading ledger...</p>}
    <TabsContent value="entries" className="grid min-w-0 gap-4 pt-3">
      <div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm text-muted-foreground">{journals.length} entries{data?.config.closedThrough ? ` / Books closed through ${data.config.closedThrough}` : ""}</span><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" disabled={!data || busy}><MoreHorizontal className="size-4" />Ledger actions</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled={!data?.can.create} onSelect={() => void run(`${root}/capture`, {})}><RefreshCw className="size-4" />Capture saved source amounts</DropdownMenuItem><DropdownMenuItem disabled={!data?.can.create} onSelect={() => newDraft()}><Plus className="size-4" />New journal</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
      <p className="text-sm text-muted-foreground">Drafts are not booked. Posting requires reviewed accounts and supporting evidence. Channel estimates are not final settlement amounts.</p>
      <div className="overflow-x-auto"><Table className="min-w-[640px]"><TableHeader><TableRow><TableHead>Date / Journal</TableHead><TableHead>Description</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Debit total</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{journals.map(entry => <TableRow key={entry.id}><TableCell><p>{entry.date}</p><p className="max-w-48 truncate text-xs" title={entry.id}>{entry.id}</p></TableCell><TableCell className="max-w-64 whitespace-normal">{entry.description}{entry.reverses && <p className="text-xs text-muted-foreground">Reversal</p>}{entry.adjusts && <p className="text-xs text-muted-foreground">Adjustment</p>}</TableCell><TableCell><Badge variant="outline">{entry.status}</Badge>{data?.ledger.journals.some(row => row.reverses === entry.id) && <Badge variant="outline">Reversed</Badge>}</TableCell><TableCell className="text-right">{money(entry.lines.reduce((sum, line) => sum + line.debitMinor, 0), entry.currency)}</TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" title="Journal actions"><MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onSelect={() => setAction({ kind: "view", entry, date: today(), reason: "", confirm: false, requestId: requestId() })}>View entry</DropdownMenuItem>{entry.status === "draft" && <><DropdownMenuItem disabled={!data?.can.post} onSelect={() => setAction({ kind: "post", entry, date: today(), reason: "", confirm: false, requestId: requestId() })}>Review and post</DropdownMenuItem><DropdownMenuItem disabled={!data?.can.create} onSelect={() => setAction({ kind: "discard", entry, date: today(), reason: "", confirm: false, requestId: requestId() })}>Discard draft</DropdownMenuItem></>}{entry.status === "posted" && <><DropdownMenuItem disabled={!data?.can.create} onSelect={() => newDraft(entry)}>Create adjustment</DropdownMenuItem><DropdownMenuItem disabled={!data?.can.reverse || Boolean(entry.reverses) || data.ledger.journals.some(row => row.reverses === entry.id)} onSelect={() => setAction({ kind: "reverse", entry, date: today(), reason: "", confirm: false, requestId: requestId() })}>Reverse entry</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div>
      {!journals.length && <p className="text-sm text-muted-foreground">No ledger entries recorded for this {returnId ? "return" : "order"}.</p>}
      <details className="min-w-0 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Saved source observations ({observations.length})</summary><div className="divide-y">{observations.map(source => <div key={source.id} className="grid gap-1 py-2 text-sm"><span>{source.kind}</span><span>{money(source.amountMinor, source.currency)} / {source.certainty}{source.postingPolicy === "reference_only" ? " / Reference only" : ""}</span><span className="break-all text-xs text-muted-foreground">{source.sourcePath} / {dateText(source.capturedAt)}</span></div>)}</div></details>
      <details className="min-w-0 border-t pt-3"><summary className="cursor-pointer text-sm font-medium">Audit history</summary><div className="divide-y">{data?.ledger.audit.slice().reverse().map(event => <div className="py-2 text-sm" key={event.id}>{event.action.replaceAll("_", " ")} / {event.actor}<p className="break-all text-xs text-muted-foreground">{dateText(event.at)} / {event.reference}</p></div>)}</div></details>
    </TabsContent>
    <TabsContent value="exports" className="grid min-w-0 gap-4 pt-3">
      <p className="text-sm text-muted-foreground">General journal CSV. Configure the receiving application's import mapping. Downloading a batch again does not create another export; exported does not mean imported.</p>
      <div className="flex flex-wrap items-end gap-2"><Label className="grid gap-2">Destination<Select value={destination} onValueChange={value => { setDestination(value); setSelected([]); setExportKey(requestId()) }}><SelectTrigger className="w-60"><SelectValue /></SelectTrigger><SelectContent>{data?.config.destinations.map(row => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select></Label><Button disabled={busy || !data?.can.export || !selected.length} onClick={() => void run(`${root}/exports`, { requestId: exportKey, destinationId: destination, journalIds: selected }, () => { setSelected([]); setExportKey(requestId()) })}><Download className="size-4" />Create export batch</Button></div>
      <div className="divide-y">{journals.filter(row => row.status === "posted").map(entry => <label key={entry.id} className="flex items-start gap-3 py-2 text-sm"><Checkbox disabled={exported(entry.id) || busy} checked={selected.includes(entry.id)} onCheckedChange={checked => { setSelected(current => checked ? [...current, entry.id] : current.filter(id => id !== entry.id)); setExportKey(requestId()) }} /><span className="min-w-0 break-words">{entry.date} / {entry.description}<span className="ml-2 text-muted-foreground">{exported(entry.id) ? "Already exported" : entry.currency}</span></span></label>)}</div>
      <div className="divide-y">{batches.map(batch => <section className="grid gap-2 py-3 text-sm" key={batch.id}><div className="flex flex-wrap justify-between gap-2"><span className="break-all font-medium">{batch.id}</span><Badge variant="outline">{batch.importedAt ? "Import confirmed" : "Exported only"}</Badge></div><p>{batch.destinationName} / {batch.entries.length} entries / {dateText(batch.createdAt)}</p><p className="break-all text-xs text-muted-foreground">SHA-256: {batch.checksum}</p>{batch.importReference && <p>Import reference: {batch.importReference}</p>}<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!data?.can.export} asChild><a href={`${root}/exports/${batch.id}.csv`}><Download className="size-4" />Download CSV</a></Button>{!batch.importedAt && <Button size="sm" variant="outline" disabled={!data?.can.export} onClick={() => { setImportBatch(batch); setImportReference("") }}>Confirm external import</Button>}</div></section>)}</div>
      {!batches.length && <p className="text-sm text-muted-foreground">No export batches.</p>}
    </TabsContent>
    <TabsContent value="settings" className="grid min-w-0 gap-4 pt-3">
      <p className="text-sm text-muted-foreground">Shared company settings. Existing export batches retain their original account mappings.</p>
      {config && <><Label className="grid max-w-xs gap-2">Books closed through<Input type="date" value={config.closedThrough} onChange={event => setConfig({ ...config, closedThrough: event.target.value })} disabled={!data?.can.configure} /></Label>{config.destinations.map((target, index) => <section key={target.id} className="grid min-w-0 gap-3 border-t pt-3"><Label className="grid gap-2">Destination name<Input value={target.name} disabled={!data?.can.configure} onChange={event => setConfig({ ...config, destinations: config.destinations.map((row, i) => i === index ? { ...row, name: event.target.value } : row) })} /></Label><p className="text-xs text-muted-foreground">Destination ID: {target.id}</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries(data?.accounts || {}).map(([key, name]) => <Label className="grid min-w-0 gap-2" key={key}>{name}<Input value={target.mappings[key] || ""} placeholder="External account name or code" disabled={!data?.can.configure} onChange={event => setConfig({ ...config, destinations: config.destinations.map((row, i) => i === index ? { ...row, mappings: { ...row.mappings, [key]: event.target.value } } : row) })} /></Label>)}</div></section>)}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!data?.can.configure || config.destinations.length >= 10} onClick={() => setConfig({ ...config, destinations: [...config.destinations, { id: `destination-${requestId().slice(0, 8)}`, name: "New destination", mappings: {} }] })}><Plus className="size-4" />Add destination</Button><Button disabled={busy || !data?.can.configure} onClick={() => void run("/api/accounting/settings", config, undefined, "PUT")}><Save className="size-4" />Save mappings</Button></div></>}
    </TabsContent>
    <Dialog open={Boolean(draft)} onOpenChange={open => !busy && !open && setDraft(null)}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>{draft?.adjusts ? "Adjustment journal" : "New journal"}</DialogTitle><DialogDescription>Save a balanced draft for review. This does not issue a refund, move stock, or notify a channel.</DialogDescription></DialogHeader>{draft && <div className="grid min-w-0 gap-4"><div className="grid gap-3 sm:grid-cols-2"><Label className="grid gap-2">Journal date<Input type="date" value={draft.date} onChange={event => setDraft({ ...draft, date: event.target.value })} /></Label><Label className="grid gap-2">Currency<Select value={draft.currency} onValueChange={value => setDraft({ ...draft, currency: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.keys(data?.currencies || {}).map(code => <SelectItem key={code} value={code}>{code}</SelectItem>)}</SelectContent></Select></Label></div><Label className="grid gap-2">Description<Input value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} /></Label><Label className="grid gap-2">Evidence / statement reference<Textarea value={draft.evidence} onChange={event => setDraft({ ...draft, evidence: event.target.value })} /></Label>
      <div className="divide-y">{draft.lines.map((line, index) => <div key={index} className="grid grid-cols-2 items-end gap-2 py-3 sm:grid-cols-[2fr_1fr_1fr_auto]"><Label className="col-span-2 grid gap-2 sm:col-span-1">Account<Select value={line.account} onValueChange={account => setDraft({ ...draft, lines: draft.lines.map((row, i) => i === index ? { ...row, account } : row) })}><SelectTrigger className="w-full"><SelectValue placeholder="Choose account" /></SelectTrigger><SelectContent>{Object.entries(data?.accounts || {}).map(([key, name]) => <SelectItem key={key} value={key}>{name}</SelectItem>)}</SelectContent></Select></Label>{(["debit", "credit"] as const).map(side => <Label key={side} className="grid gap-2">{side === "debit" ? "Debit" : "Credit"}<Input inputMode="decimal" value={line[side]} onChange={event => setDraft({ ...draft, lines: draft.lines.map((row, i) => i === index ? { ...row, [side]: event.target.value } : row) })} /></Label>)}<Button variant="ghost" size="icon" title="Remove line" disabled={draft.lines.length <= 2} onClick={() => setDraft({ ...draft, lines: draft.lines.filter((_, i) => i !== index) })}><Trash2 className="size-4" /></Button></div>)}</div><Button variant="outline" disabled={draft.lines.length >= 100} onClick={() => setDraft({ ...draft, lines: [...draft.lines, emptyLine()] })}><Plus className="size-4" />Add line</Button>
      <fieldset className="grid gap-2"><legend className="mb-2 text-sm font-medium">Source observations</legend>{observations.map(source => <label className="flex items-start gap-2 text-sm" key={source.id}><Checkbox disabled={["unknown", "pending"].includes(source.certainty) || source.postingPolicy === "reference_only"} checked={draft.sourceIds.includes(source.id)} onCheckedChange={checked => setDraft({ ...draft, sourceIds: checked ? [...draft.sourceIds, source.id] : draft.sourceIds.filter(id => id !== source.id) })} /><span>{source.kind} / {money(source.amountMinor, source.currency)} / {source.certainty}{source.postingPolicy === "reference_only" ? " / Reference only" : ""}</span></label>)}</fieldset>
    <p role="status" className="text-sm">{balance ? `Debit ${money(balance.debit, draft.currency)} / Credit ${money(balance.credit, draft.currency)} / ${balance.balanced ? "Balanced" : "Not balanced"}` : "Enter valid amounts."}</p></div>}<DialogFooter className="sticky bottom-0 bg-background pb-[max(0.75rem,env(safe-area-inset-bottom))]"><Button variant="outline" disabled={busy} onClick={() => setDraft(null)}>Cancel</Button><Button disabled={busy || !draft?.description || !draft.evidence || !balance?.balanced || draft.lines.some(line => !line.account)} onClick={() => draft && void run(`${root}/journals`, { ...draft, ...(returnId ? { returnId } : {}) }, () => setDraft(null))}>Save draft</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(action)} onOpenChange={open => !busy && !open && setAction(null)}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{action?.kind === "view" ? "Journal entry" : `${action?.kind || "Review"} journal`}</DialogTitle><DialogDescription className="break-all">{action?.entry.id}</DialogDescription></DialogHeader>{action && <div className="grid min-w-0 gap-3"><p>{action.entry.description}</p><p className="whitespace-pre-wrap text-sm text-muted-foreground">Evidence: {action.entry.evidence}</p><p className="text-sm">Created by: {action.entry.createdBy}{action.entry.postedBy ? ` / Posted by: ${action.entry.postedBy}` : ""}</p>{lineTable(action.entry)}{entrySources(action.entry)}{action.kind === "reverse" && <><Label className="grid gap-2">Reversal date<Input type="date" value={action.date} onChange={event => setAction({ ...action, date: event.target.value })} /></Label><Label className="grid gap-2">Reason<Textarea value={action.reason} onChange={event => setAction({ ...action, reason: event.target.value })} /></Label></>}{action.kind !== "view" && <label className="flex items-start gap-2 text-sm"><Checkbox checked={action.confirm} onCheckedChange={checked => setAction({ ...action, confirm: checked === true })} />I reviewed the accounts, amounts, and supporting evidence and confirm this action.</label>}</div>}<DialogFooter className="sticky bottom-0 bg-background"><Button variant="outline" disabled={busy} onClick={() => setAction(null)}>Close</Button>{action && action.kind !== "view" && <Button disabled={busy || !action.confirm || (action.kind === "reverse" && !action.reason)} onClick={() => void run(`${root}/journals/${action.entry.id}/${action.kind}`, { confirm: action.confirm, reason: action.reason, date: action.date, requestId: action.requestId }, () => setAction(null))}>{action.kind === "post" ? "Post immutable entry" : action.kind === "reverse" ? "Create reversal" : "Discard draft"}</Button>}</DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(importBatch)} onOpenChange={open => !busy && !open && setImportBatch(null)}><DialogContent><DialogHeader><DialogTitle>Confirm external import</DialogTitle><DialogDescription>Record the reference returned by your accounting software after a successful import.</DialogDescription></DialogHeader><Label className="grid gap-2">Import reference<Input value={importReference} onChange={event => setImportReference(event.target.value)} /></Label><DialogFooter><Button variant="outline" onClick={() => setImportBatch(null)}>Cancel</Button><Button disabled={busy || !importReference} onClick={() => importBatch && void run(`${root}/exports/${importBatch.id}/confirm`, { reference: importReference }, () => setImportBatch(null))}>Confirm import</Button></DialogFooter></DialogContent></Dialog>
  </Tabs>
}
