import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'

type Summary = { lineCount?: number; orderCount?: number; salesMinor?: number; missingCostLines?: number; errors?: number; warnings?: number; newLines?: number; duplicateLines?: number; insertedLines?: number }
type Preview = { id: string; status: string; previewToken?: string; filename: string; source: string; sheet: string; headers: string[]; fields: string[]; mapping: Record<string,string>; sample: Record<string,unknown>[]; summary: Summary; issues: { row: number; level: string; message: string }[] }
type Batch = { id: string; source: string; filename: string; status: string; summary: Summary; created_at: string }
type Report = { summary: { lines: number; orders: number; sales_minor: string; known_cost_minor: string; missing_cost_lines: number; known_profit_minor: string }; rows: { source: string; order_id: string; date: string; customer: string; status: string; lines: number; sales_minor: string; cost_minor: string | null }[]; hasMore: boolean }
const labels: Record<string,string> = { orderId:'Source order number *',lineId:'Source line ID (required for repeated SKUs)',date:'Order date *',sku:'SKU *',quantity:'Quantity *',unitPrice:'Unit selling price',sales:'Extended sales',unitCost:'Historical unit cost',cost:'Historical extended cost',customer:'Customer',reference:'External reference',status:'Source status',description:'Description',vendor:'Supplier',uom:'Unit / pack',reportedProfit:'Source profit (audit only)' }
async function api<T>(url:string,method='GET',body?:unknown):Promise<T>{const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error || 'Request failed.');return data}
const money=(minor: string | number | null | undefined,currency:string)=>minor===null || minor===undefined?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(minor)/100)

export function ManualOrderImporter({base,companyName,currency,owner}:{base:string;companyName:string;currency:string;owner?:boolean}) {
  const [tab,setTab]=useState('import'),[batches,setBatches]=useState<Batch[]>([]),[report,setReport]=useState<Report|null>(null)
  const [source,setSource]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[mapping,setMapping]=useState<Record<string,string>>({})
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[page,setPage]=useState(1)
  const [filters,setFilters]=useState({from:'',to:'',status:'',source:''}),[applied,setApplied]=useState(filters)
  const [confirm,setConfirm]=useState<{kind:'apply'|'rollback';id:string}|null>(null)
  const [orderDetail,setOrderDetail]=useState<{orderId:string;rows:{batch_id:string;data:{lineId:string;sku:string;description:string;quantity:number;uom:string;salesMinor:number;costMinor:number|null;vendor:string;status:string}}[]}|null>(null)
  useEffect(()=>{let cancelled=false;setError('');Promise.all([api<{rows:Batch[]}>(`${base}/order-imports`),api<Report>(`${base}/imported-orders?${new URLSearchParams({...applied,page:String(page)})}`)]).then(([history,data])=>{if(!cancelled){setBatches(history.rows);setReport(data)}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[base,revision,page,applied])
  async function run(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Unable to complete request.')}finally{setBusy(false)}}
  async function upload(){
    if(!file)return
    if(file.size>10*1024*1024)throw new Error('File exceeds 10 MB. Split the export before importing.')
    const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Unable to read file.'));reader.readAsDataURL(file)})
    const next=await api<Preview>(`${base}/order-imports`,'POST',{source,filename:file.name,content})
    setPreview(next);setMapping(next.mapping);setRevision(n=>n+1)
  }
  async function openBatch(batch:Batch){const next=await api<Preview>(`${base}/order-import-detail?batchId=${batch.id}`);setPreview(next);setMapping(next.mapping);setTab('import')}
  const editable=preview && ['uploaded','preview'].includes(preview.status) && owner
  return <section className="min-w-0 space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="text-lg font-semibold">Manual order importer</h3><p className="break-words text-sm text-muted-foreground">{companyName} · Reporting-only orders · {currency}</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button disabled={busy}>Actions</Button></DropdownMenuTrigger><DropdownMenuContent align="end">{owner && <DropdownMenuItem onClick={()=>{setPreview(null);setFile(null);setTab('import')}}>New import</DropdownMenuItem>}<DropdownMenuItem onClick={()=>setRevision(n=>n+1)}>Refresh</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
    <p className="text-sm text-muted-foreground">Imported orders retain their source status and historical costs. They do not reserve stock, create purchase orders, post accounting entries, or send marketplace updates. These totals cover manual imports only.</p>
    {error && <p role="alert" className="rounded-md border border-destructive p-3 text-sm text-destructive">{error}</p>}{notice && <p role="status" className="text-sm">{notice}</p>}{busy && <p role="status" className="text-sm">Processing…</p>}
    <Tabs value={tab} onValueChange={setTab}><TabsList className="grid w-full grid-cols-1 gap-1 group-data-horizontal/tabs:h-auto sm:w-fit sm:grid-cols-3"><TabsTrigger value="orders">Imported orders</TabsTrigger><TabsTrigger value="import">Upload & mapping</TabsTrigger><TabsTrigger value="history">Import history</TabsTrigger></TabsList>
      <TabsContent value="orders" className="space-y-4">
        <form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5" onSubmit={e=>{e.preventDefault();setPage(1);setApplied({...filters})}}>
          <div className="space-y-1"><Label htmlFor="manual-from">From</Label><Input id="manual-from" type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></div>
          <div className="space-y-1"><Label htmlFor="manual-to">To (inclusive)</Label><Input id="manual-to" type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></div>
          <div className="space-y-1"><Label htmlFor="manual-source-filter">Source system</Label><Input id="manual-source-filter" value={filters.source} onChange={e=>setFilters({...filters,source:e.target.value})} placeholder="All sources"/></div>
          <div className="space-y-1"><Label htmlFor="manual-status">Exact source status</Label><Input id="manual-status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} placeholder="All statuses"/></div><Button className="self-end" disabled={busy}>Apply filters</Button>
        </form>
        {report && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Orders',report.summary.orders],['Sales',money(report.summary.sales_minor,currency)],['Product gross profit',report.summary.missing_cost_lines?'Unknown — missing costs':money(report.summary.known_profit_minor,currency)],['Missing-cost lines',`${report.summary.missing_cost_lines} / ${report.summary.lines}`]].map(([label,value])=><div key={String(label)} className="rounded-md border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="break-words font-semibold">{value}</p></div>)}</div>
          <p className="text-xs text-muted-foreground">Product gross profit excludes shipping, taxes, marketplace fees, and other expenses. All source statuses are included unless filtered. Counts under a status filter reflect matching lines.</p>
          <div className="max-w-full overflow-x-auto"><Table><TableHeader><TableRow>{['Source / order','Date','Customer','Source status','Lines','Sales','Historical cost'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{report.rows.map(row=><TableRow key={`${row.source}/${row.order_id}`}><TableCell className="max-w-52 break-words whitespace-normal"><Button variant="link" className="h-auto whitespace-normal p-0 text-left" disabled={busy} onClick={()=>void run(async()=>{const detail=await api<{rows:NonNullable<typeof orderDetail>["rows"]}>(`${base}/imported-order-lines?${new URLSearchParams({source:row.source,orderId:row.order_id})}`);setOrderDetail({orderId:row.order_id,rows:detail.rows})})}>{row.source} / {row.order_id}</Button></TableCell><TableCell>{row.date}</TableCell><TableCell className="max-w-48 break-words whitespace-normal">{row.customer}</TableCell><TableCell className="max-w-40 break-words whitespace-normal">{row.status}</TableCell><TableCell>{row.lines}</TableCell><TableCell>{money(row.sales_minor,currency)}</TableCell><TableCell>{money(row.cost_minor,currency)}</TableCell></TableRow>)}</TableBody></Table></div>
          {!report.rows.length && <p className="text-sm">No manually imported orders match these filters.</p>}<div className="flex items-center gap-3"><Button variant="outline" disabled={busy||page===1} onClick={()=>setPage(n=>n-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={busy||!report.hasMore} onClick={()=>setPage(n=>n+1)}>Next</Button></div>
        </>}
      </TabsContent>
      <TabsContent value="import" className="space-y-4">
        {!preview && owner && <div className="space-y-3 rounded-md border p-4"><p className="text-sm">One row per order line. CSV, XLSX, or XLS; first worksheet; headers in the first row. Maximum 10 MB and 10,000 lines. All amounts must be in {currency}.</p><Label htmlFor="manual-source">Source system name</Label><Input id="manual-source" value={source} maxLength={100} onChange={e=>setSource(e.target.value)} placeholder="e.g. outside-sales-system"/><p className="text-xs text-muted-foreground">Reuse this name for future exports from the same system so duplicate checks work.</p><Label htmlFor="manual-file">Order export</Label><Input id="manual-file" type="file" accept=".csv,.xlsx,.xls" onChange={e=>setFile(e.target.files?.[0] || null)}/><Button disabled={busy||!file||!source.trim()} onClick={()=>void run(upload)}>Upload and map columns</Button></div>}
        {!preview && !owner && <p>An organization owner can upload orders. You can view imported orders and history.</p>}
        {preview && <><div className="rounded-md border p-3 text-sm"><p className="break-words font-medium">Import #{preview.id} — {preview.filename}</p><p className="break-words">Destination: {companyName} · Source: {preview.source} · Worksheet: {preview.sheet}</p><p>Status: {preview.status}</p></div>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{preview.fields.map(field=><div key={field} className="min-w-0 space-y-1"><Label htmlFor={`mapping-${field}`}>{labels[field] || field}</Label><select id={`mapping-${field}`} disabled={busy||!editable} className="h-10 w-full min-w-0 rounded-md border bg-background px-2" value={mapping[field] || ''} onChange={e=>{setMapping({...mapping,[field]:e.target.value});setPreview({...preview,status:'uploaded',summary:{},issues:[]})}}><option value="">Not mapped</option>{preview.headers.map(h=><option key={h} value={h}>{h}</option>)}</select></div>)}</div>
          <details className="rounded-md border p-3 text-sm"><summary>Source sample (first five rows)</summary><div className="max-w-full overflow-auto"><Table><TableHeader><TableRow>{preview.headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{preview.sample.map((row,i)=><TableRow key={i}>{preview.headers.map(h=><TableCell key={h}>{String(row[h]??'')}</TableCell>)}</TableRow>)}</TableBody></Table></div></details>
          {editable && <Button disabled={busy} variant="outline" onClick={()=>void run(async()=>{const next=await api<Preview>(`${base}/order-import-preview`,'POST',{batchId:preview.id,mapping});setPreview(next)})}>Validate and preview</Button>}
          {preview.summary.lineCount!==undefined && <div className="space-y-2 rounded-md border p-3 text-sm"><p>{preview.summary.orderCount} orders · {preview.summary.lineCount} valid lines · {money(preview.summary.salesMinor,currency)} source sales</p><p>{preview.summary.newLines} new lines · {preview.summary.duplicateLines} unchanged duplicates · {preview.summary.missingCostLines} missing-cost lines</p><p>{preview.summary.errors} errors · {preview.summary.warnings} warnings</p><p>Preview totals describe this file, including duplicates. Only new lines contribute additional reporting totals.</p></div>}
          {!!preview.issues.length && <div className="max-h-72 space-y-2 overflow-y-auto rounded-md border p-3">{preview.issues.map((issue,i)=><p key={i} className={`break-words text-sm ${issue.level==='error'?'text-destructive':'text-muted-foreground'}`}>Row {issue.row} — {issue.level}: {issue.message}</p>)}<p className="text-xs text-muted-foreground">Showing the first 100 issues. Full issue counts appear above.</p></div>}
          {editable && preview.status==='preview' && <Button disabled={busy||Boolean(preview.summary.errors)} onClick={()=>setConfirm({kind:'apply',id:preview.id})}>Review import into {companyName}</Button>}
        </>}
      </TabsContent>
      <TabsContent value="history" className="space-y-3"><p className="text-sm text-muted-foreground">Latest 100 imports for {companyName}. Rollback removes only the lines added by that batch from reports and retains the audit history.</p>{batches.map(batch=><div key={batch.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3"><div className="min-w-0"><p className="break-words font-medium">#{batch.id} — {batch.filename}</p><p className="text-sm">{batch.source} · {batch.status} · {new Date(batch.created_at).toLocaleString()}</p><p className="text-xs text-muted-foreground">{batch.summary.insertedLines??0} inserted lines</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" disabled={busy}>Import actions</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>void run(()=>openBatch(batch))}>View / resume</DropdownMenuItem>{owner&&batch.status==='applied'&&<DropdownMenuItem onClick={()=>setConfirm({kind:'rollback',id:batch.id})}>Roll back batch</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></div>)}</TabsContent>
    </Tabs>
    <Dialog open={Boolean(confirm)} onOpenChange={open=>{if(!open&&!busy)setConfirm(null)}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{confirm?.kind==='apply'?'Confirm manual order import':'Roll back import'}</DialogTitle><DialogDescription className="break-words">Company: {companyName}. Batch #{confirm?.id}. {confirm?.kind==='apply'?'New lines will be added to reporting only. Unchanged duplicates will be skipped.':'Lines created by this batch will be excluded from reporting. Other batches will remain unchanged.'}</DialogDescription></DialogHeader>{confirm?.kind==='apply'&&preview&&<p className="text-sm">{preview.summary.newLines} new lines; {preview.summary.duplicateLines} duplicates; {preview.summary.warnings} warnings.</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<DialogFooter className="pb-[env(safe-area-inset-bottom)]"><Button variant="outline" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</Button><Button disabled={busy} onClick={()=>void run(async()=>{if(!confirm)return;const result=await api<{status:string}>(`${base}/order-import-${confirm.kind}`,'POST',{batchId:confirm.id,confirm:true,previewToken:preview?.previewToken});setNotice(`Import #${confirm.id}: ${result.status}.`);setConfirm(null);setPreview(null);setRevision(n=>n+1);setTab('history')})}>Confirm {confirm?.kind==='apply'?'import':'rollback'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(orderDetail)} onOpenChange={open=>{if(!open)setOrderDetail(null)}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Imported order {orderDetail?.orderId}</DialogTitle><DialogDescription>{companyName} — historical source lines</DialogDescription></DialogHeader><div className="max-w-full overflow-x-auto"><Table><TableHeader><TableRow>{['Line / SKU','Description','Qty / unit','Sales','Cost','Supplier / status','Batch'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{orderDetail?.rows.map(({batch_id,data})=><TableRow key={data.lineId}><TableCell className="break-words whitespace-normal">{data.lineId} / {data.sku}</TableCell><TableCell className="max-w-64 break-words whitespace-normal">{data.description}</TableCell><TableCell>{data.quantity} {data.uom}</TableCell><TableCell>{money(data.salesMinor,currency)}</TableCell><TableCell>{money(data.costMinor,currency)}</TableCell><TableCell className="break-words whitespace-normal">{data.vendor} / {data.status}</TableCell><TableCell>#{batch_id}</TableCell></TableRow>)}</TableBody></Table></div></DialogContent></Dialog>
  </section>
}
