import { FileText } from "lucide-react"
import { Input } from "./ui/input"
import { Label } from "./ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs"
import { ReturnTransactions } from "./order-transactions"

type Row = Record<string, unknown>
const rows = (value: unknown): Row[] => Array.isArray(value) ? value as Row[] : []
const money = (value: unknown, currency: unknown) => new Intl.NumberFormat("en-US", { style: "currency", currency: String(currency || "USD") }).format(Number(value || 0))

export function OrderReturnDetails({ record, trackingUrl, defaultTab = "details" }: { record: Row; trackingUrl: (row: Row, carrier: string, number: string) => string; defaultTab?: "details" | "transactions" }) {
  const attachments = rows(record.attachments)
  return <section className="min-w-0 basis-full border-t pt-3 text-sm">
    <Tabs defaultValue={defaultTab} className="min-w-0"><TabsList><TabsTrigger value="details">Details</TabsTrigger><TabsTrigger value="transactions">Transactions</TabsTrigger></TabsList><TabsContent value="details" className="min-w-0 pt-3">
    <dl className="grid gap-3 sm:grid-cols-3">
      <div><dt className="text-muted-foreground">Channel return</dt><dd className="break-all">{String(record.source || "Local")} {String(record.channelReturnId || "")}</dd><dd>{String(record.channelStatus || "Local only")}</dd></div>
      <div><dt className="text-muted-foreground">Refund</dt><dd>{record.refundAmountUnverified ? "Amount awaiting verification" : record.actualRefundAmount != null ? `${money(record.actualRefundAmount, record.currency)} confirmed` : `${money(record.estimatedRefundAmount ?? record.amount, record.currency)} estimated`}</dd></div>
      <div><dt className="text-muted-foreground">Warehouse receiving</dt><dd>{String(record.receivingStatus || (record.receivedAt ? "Received" : "Not received in DataPlus"))}</dd></div>
    </dl>
    {Boolean(record.reason || record.note) && <div className="mt-3 grid gap-3 rounded-md border bg-muted/20 p-3 sm:grid-cols-2">{Boolean(record.reason) && <div><p className="text-xs font-medium uppercase text-muted-foreground">Return reason</p><p className="mt-1 whitespace-pre-wrap">{String(record.reason)}</p></div>}{Boolean(record.note) && <div><p className="text-xs font-medium uppercase text-muted-foreground">Return notes</p><p className="mt-1 whitespace-pre-wrap">{String(record.note)}</p></div>}</div>}
    <div className="mt-3 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>SKU / Item</TableHead><TableHead>Requested</TableHead><TableHead>Received</TableHead></TableRow></TableHeader><TableBody>{rows(record.items).map((line, index) => <TableRow key={index}><TableCell><span className="font-medium">{String(line.sku || "Unmatched SKU")}</span><p className="max-w-80 whitespace-normal text-muted-foreground">{String(line.title || "")}</p></TableCell><TableCell>{Number(line.qty || 0)}</TableCell><TableCell>{Number(line.receivedQty || 0)}</TableCell></TableRow>)}</TableBody></Table></div>
    {rows(record.returnTracking).map((tracking, index) => { const url = trackingUrl(tracking, String(tracking.carrier || ""), String(tracking.trackingNumber || "")); return <p className="mt-2 break-all" key={index}>{String(tracking.carrier || "Carrier not supplied")} / {url ? <a className="text-primary underline" href={url} target="_blank" rel="noopener noreferrer">{String(tracking.trackingNumber)}</a> : String(tracking.trackingNumber || "")} <span className="text-muted-foreground">{String(tracking.status || "")}</span></p> })}
    {rows(record.receiptHistory).length > 0 && <details className="mt-3 border-t pt-3"><summary className="cursor-pointer font-medium">Receiving history ({rows(record.receiptHistory).length})</summary>{rows(record.receiptHistory).map(receipt => <div key={String(receipt.id)} className="border-b py-2"><p>{String(receipt.at)} / {String(receipt.user)}</p><p>{String(receipt.condition)} / {String(receipt.disposition)} / {String(receipt.binLocation || "No bin")}</p>{rows(receipt.items).map((line, index) => <p key={index}>{String(line.sku)}: {Number(line.receivedQty || 0)} received total</p>)}</div>)}</details>}
    {attachments.length > 0 && <div className="mt-3 grid gap-2 border-t pt-3 sm:grid-cols-2">{attachments.map((file, index) => { const href = String(file.dataUrl || file.url || ""); const isImage = /^data:image\/(jpeg|png|webp);base64,/i.test(href) || String(file.mimeType || "").startsWith("image/"); return <a key={String(file.id || `${file.name}-${index}`)} href={href || undefined} target="_blank" rel="noopener noreferrer" className="flex min-w-0 items-center gap-3 rounded-md border bg-background p-2 hover:bg-muted/40">{isImage && href ? <img className="size-14 shrink-0 rounded object-cover" src={href} alt={String(file.name || "Return evidence")} /> : <span className="flex size-14 shrink-0 items-center justify-center rounded bg-muted"><FileText className="size-6 text-muted-foreground" /></span>}<span className="min-w-0"><span className="block truncate font-medium">{String(file.name || "Return attachment")}</span><span className="block text-xs text-muted-foreground">{String(file.mimeType || "Attachment")}{Number(file.size || 0) > 0 ? ` / ${(Number(file.size) / 1024 / 1024).toFixed(2)} MB` : ""}</span></span></a> })}</div>}
    </TabsContent><TabsContent value="transactions" className="min-w-0 pt-3"><ReturnTransactions record={record} /></TabsContent></Tabs>
  </section>
}

export function ReturnReceiptFields({ record, warehouses, draft, setDraft }: { record: Row | null; warehouses: Row[]; draft: Record<string, string>; setDraft: (next: Record<string, string>) => void }) {
  const physical = warehouses.filter((row) => row.isPhysical !== false && row.allowReceiving !== false && row.active !== false && String(row.status).toLowerCase() !== "inactive" && !/virtual|supplier|transfer/i.test(String(row.type || row.warehouseType || "") + String(row.inventorySourceType || "")) && !/datawarehouse/i.test(String(row.name || "")))
  return <section className="grid gap-3 border-t pt-3">
    <Label>Receiving warehouse<Select value={draft.warehouseId || ""} onValueChange={(warehouseId) => setDraft({ ...draft, warehouseId })}><SelectTrigger><SelectValue placeholder="Choose physical warehouse" /></SelectTrigger><SelectContent>{physical.map((row) => <SelectItem key={String(row.id)} value={String(row.id)}>{String(row.name)}</SelectItem>)}</SelectContent></Select></Label>
    <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>SKU</TableHead><TableHead>Requested</TableHead><TableHead>Physically received</TableHead></TableRow></TableHeader><TableBody>{rows(record?.items).map((line, index) => <TableRow key={index}><TableCell>{String(line.sku || "Unmatched SKU")}</TableCell><TableCell>{Number(line.qty || 0)}</TableCell><TableCell><Input aria-label={`Received ${String(line.sku || index)}`} className="w-24" type="number" min={0} max={Number(line.qty || 0)} step={1} disabled={Boolean(record?.restockedAt)} value={draft[`received-${index}`] ?? String(line.receivedQty || 0)} onChange={(event) => setDraft({ ...draft, [`received-${index}`]: event.target.value })} /></TableCell></TableRow>)}</TableBody></Table></div>
  </section>
}
