import { useEffect, useState } from 'react'
import { ManualChannels } from './manual-channels'
import { Button } from './ui/button'
import { Input } from './ui/input'
import { Label } from './ui/label'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from './ui/dialog'
export type SavedOrderTemplate = {id:string;name:string;channel_id:string;mapping:Record<string,string>;updated_at:string}
export async function templateRequest<T>(url:string,method='GET',body?:unknown):Promise<T> {
  const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)})
  const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to save template.');return data
}
export function SaveOrderTemplate({base,companyName,mapping,channelId,existing,onSaved,onClose}:{base:string;companyName:string;mapping:Record<string,string>;channelId:string;existing?:SavedOrderTemplate;onSaved:()=>void;onClose:()=>void}) {
  const [name,setName]=useState(existing?.name||''),[channel,setChannel]=useState(channelId),[busy,setBusy]=useState(false),[error,setError]=useState('')
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{existing?'Edit import template':'Save mapping as template'}</DialogTitle><DialogDescription>{companyName}. Save column mappings for future uploads. Each upload still requires validation and confirmation.</DialogDescription></DialogHeader><Label htmlFor="order-template-name">Template name</Label><Input id="order-template-name" value={name} maxLength={100} placeholder="e.g. Zoro order export" onChange={e=>setName(e.target.value)}/><ManualChannels base={base} companyName={companyName} owner picker value={channel} onChange={setChannel}/><p className="text-xs text-muted-foreground">Channel assignment applies to future imports. Existing batches keep their original source.</p>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<DialogFooter className="pb-[env(safe-area-inset-bottom)]"><Button variant="outline" disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={busy||!name.trim()||!channel} onClick={()=>{setBusy(true);setError('');void templateRequest(`${base}/order-import-templates`,existing?'PATCH':'POST',{id:existing?.id,name,channelId:channel,mapping}).then(()=>{onSaved();onClose()}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>Save template</Button></DialogFooter></DialogContent></Dialog>
}
export function SavedOrderTemplates({base,companyName,owner}:{base:string;companyName:string;owner:boolean}) {
  const [rows,setRows]=useState<SavedOrderTemplate[]>([]),[channels,setChannels]=useState<{id:string;name:string;enabled:boolean}[]>([]),[edit,setEdit]=useState<SavedOrderTemplate|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState('')
  useEffect(()=>{let cancelled=false;Promise.all([templateRequest<{rows:SavedOrderTemplate[]}>(`${base}/order-import-templates`),templateRequest<{rows:typeof channels}>(`${base}/order-import-channels`)]).then(([templates,sources])=>{if(!cancelled){setRows(templates.rows);setChannels(sources.rows)}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[base,revision])
  return <section className="mb-6 space-y-3"><h3 className="font-semibold">Saved mapping templates</h3><p className="text-sm text-muted-foreground">{companyName}. Save a mapping from Upload & mapping, then select it for the assigned channel on your next upload.</p>{error&&<p role="alert">{error}</p>}{!rows.length&&<p className="text-sm">No saved mappings yet.</p>}{rows.map(row=>{const channel=channels.find(c=>c.id===row.channel_id);return <div key={row.id} className="space-y-2 rounded-md border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="min-w-0"><p className="break-words font-medium">{row.name}</p><p className="break-words text-sm text-muted-foreground">{channel?.name||'Unavailable channel'}{channel&&!channel.enabled?' - Disabled':''}</p></div>{owner&&<Button variant="outline" onClick={()=>setEdit(row)}>Edit template</Button>}</div><details className="text-sm"><summary>Saved field mappings</summary>{Object.entries(row.mapping).filter(([,column])=>column).map(([field,column])=><p key={field} className="break-words">{field}: {column}</p>)}</details></div>})}{edit&&<SaveOrderTemplate base={base} companyName={companyName} existing={edit} mapping={edit.mapping} channelId={edit.channel_id} onClose={()=>setEdit(null)} onSaved={()=>setRevision(n=>n+1)}/>}</section>
}
