export const settingsTabItems = [
    { id: "operations", label: "Operations" },
    { id: "organization", label: "Organization" },
    { id: "companies", label: "Companies" },
    { id: "orders", label: "Orders" },
    { id: "purchasing", label: "Purchasing" },
    { id: "inventory", label: "Inventory" },
    { id: "fulfillment", label: "Fulfillment" },
    { id: "notifications", label: "Notifications" },
    { id: "security", label: "Security" },
    { id: "jobs", label: "Jobs" },
    { id: "worker", label: "Worker" },
    { id: "backups", label: "Backups" },
    { id: "catalog", label: "Catalog" },
    { id: "data-sources", label: "Data sources" },
    { id: "barcode", label: "Barcode lookups" },
    { id: "ai", label: "AI integration" },
    { id: "email", label: "Email" },
    { id: "users", label: "Users" },
    { id: "releases", label: "Releases" },
  ]
